### ISSUE TITLE
placing ggvisOutput in server.R under renderUI fails

### ISSUE THREAD

**Issue by moosilauke18** [rstudio/ggvis#165]
in server.R I have a renderUI function as below.  If I place the 

```
ggvisOutput("name of graph")
```

within ui.R it displays fine as does a ggplot2; however the following doesn't show up., while placing a ggplot2 in place works.

```
output$Mode_Graph <- renderUI({
    ggvisOutput("name of graph")
    })
```

**Comment by adimajo** [comment]
Unfortunately this still happens; tested on Windows and Mac OS...
It's rather annoying since I have to loop over lots of datasets / models / metrics to plot... Any idea? Willing to spend some time on this.

sessionInfo()
R Under development (unstable) (2020-02-26 r77861)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Catalina 10.15.4

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ggvis_0.4.5  magrittr_1.5 shiny_1.4.0
