### ISSUE TITLE
ggvis state of development

### ISSUE THREAD

**Issue by geotheory** [rstudio/ggvis#471]
Is it possible to get an update on the state of development of ggvis - still at 0.4.3? We've seen relatively few commits since 2015, and I'm not aware of any update since [issue 388](https://github.com/rstudio/ggvis/issues/388) on this question, when Hadley said further work was expected. Maybe I missed something.  Is ggvis essentially in the same place as ggplot2 - passed over to the community?

I ask because questions around community and support are big factors when deciding between a Shiny strategy and one focussed on D3/crossfilter/etc javascript skillsets.

**Comment by vikram-rawat** [comment]
Me too...

I respect hadley and would understand if he just could not give time to this project. I would understand it. But at least as a community we want to know is it worth learning???

I am new to R and want to know if this package has a future.

A very simple and non rude question.

I hope any of you would reply. Please let us know...

**Comment by nicholasjhorton** [comment]
I'm confident that whenever ggvis2 sees the light of day it will continue to advance the state of the art (as ggvis, ggplot2, and other @hadley tidyverse packages have done so effectively).  But one can't rush greatness.

In the interim, @rpruim and Danny Kaplan have implemented a prototype of "ggformula" that might spark some interest in future interfaces (see https://github.com/ProjectMOSAIC/ggformula and the vignette within).  Comments and suggestions welcomed in https://github.com/ProjectMOSAIC/ggformula/issues

**Comment by vikram-rawat** [comment]
I am sorry bariatte but i am not able to understand what you meant by that.

What i wanted to say was that I am still not able to produce a decent box plot in ggvis. When i change the size of boxes they move away from the line. I posted it one month ago and nobody replied. 

Then i saw the code base and most of the files were updates 3 years ago. So i had a doubt what if everybody has left the package and i am excited about it for no reason.

Anyways is there any good interactive package that is production ready where i can change almost everything that i want just like ggplot2.

**Comment by pssguy** [comment]
@vikram-rawat . As I understand it, ggvis was an RStudio  priority some time ago but no longer is on the roadmap. The guys there have not exactly been sitting with their legs up though!

 I suggest you move on to other alternatives e.g. plotly, highcharter ...

**Comment by briatte** [comment]
Dear @vikram-rawat 

I meant that it is generally unwise to try to use code that has not been updated for a long time, especially when the code calls packages that have evolved a lot since.

**Comment by vikram-rawat** [comment]
@briatte and @pssguy thanks guys

I will surely try plotly and highcharter.

I have come from an excel Background and 

In the open source everything seems quite different. It's Killing me to find that there are thousand packages you have to keep track of just to solve simple statistics. Now there are packages which are not fully developed.

well the funny part is I chose R instead of Python because I didn't wanted to be a developer. Now I feel like one already. 
:-)
:-)
:-)

Thanks for quick reply

**Comment by donk3yzz** [comment]
I am wondering the same question as well. I fell in love with this package as long as I saw it in ZhiHu but  these days I take a look at other packages like ggformula and plotly, they both have the similar grammar with ggvis, I can't tell which of them is better but plotly has been widely used not only in R but python and js. I think maybe that's why ggvis is given up.

**Comment by briatte** [comment]
Interesting commit today:

https://github.com/rstudio/ggvis/compare/da9d34dd49...0437ede7a0
